name: CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
     branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        
    - name: Install & Test
      run: |
        pip install -r requirements.txt
        pip install pytest
   
  cd:
    runs-on: ubuntu-latest
    needs: ci
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Build
        run: docker build -t cifar10_app .
        
      - name: Tags
        run: |
          docker tag cifar10_app ${{ secrets.DOCKER_USER }}/cifar10_app:${{ github.sha }}
          docker tag cifar10_app ${{ secrets.DOCKER_USER }}/cifar10_app:latest
          
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/cifar10_app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/cifar10_app:latest
          
